### ISSUE TITLE
Integrate winch controller with 1 point model

### ISSUE THREAD

**Issue by ufechner7** [ufechner7/KiteModels.jl#37]
The winch controller is already integrated in KPS4, but not yet in KPS3.

TODO:
- [x] add length and v_reelout to the vector y, parameter of the function residual!() in KPS3.jl
- [x] fix bench3.jl
- [x] fix example/reel_out for 1p kite model
- [ ] document the reel-out examples for 1p and 4p model

**Comment by ufechner7** [comment]
I think it is not difficult to fix, so I will try to do it this month (Oct 2022). But that does not mean that the autopilot will work already with the one point model because for this also changes to the currently hardcoded parameters of the autopilot are needed. I try my best!

**Comment by ufechner7** [comment]
I added the example https://github.com/aenarete/KiteControllers.jl/blob/main/examples/autopilot_1p.jl to the KiteControllers repository... It kind-of works, but at the end of the reel-in phase the kite crashes...
Perhaps I just need different controller parameters to fix that. I will investigate this.

**Comment by jcrismer** [comment]
Thank you for investigating that @ufechner7  ! Do you have any news since then ?

**Comment by ufechner7** [comment]
TODO:
[ ] - fix example/reel_out for 1p kite model

**Comment by ufechner7** [comment]
Started implementation of this feature in the branch "winch"...
