### ISSUE TITLE
Understanding the state initialization process

### ISSUE THREAD

**Issue by jcrismer** [ufechner7/KiteModels.jl#41]
Some things are not clear to me regarding the state initializations in Kitemodels.jl . In `find_steady_state!`, why do we have `s.stiffness_factor=stiffness_factor` and then `s.stiffness_factor=1.0` ?
Also I do not really get why `find_steady_state_inner` is called twice ?

Thanks in advance for your help.

**Comment by ufechner7** [comment]
I try to explain: If we execute find_steady_state_inner only once with the full stiffness (s.stiffness_factor=1.0) then it will fail to converge. This is a problem too hard for the chosen solver. But if the stiffness of the springs of the tether is lower it can find an intermediate solution, but the solution is not very accurate. So running find_steady_state_inner a second time with the intermediate solution as initial vector allows it to converge and to find an accurate final initial solution.
