### ISSUE TITLE
Three-wire-kite

### ISSUE THREAD

**Issue by ufechner7** [ufechner7/KiteModels.jl#45]
Is there any possibility to simulate a kite that has 3 wires going from the ground to the kite, so using three ground-based motors, instead of using a control pod in the air? If so, how could one implement this?

**Comment by 1-Bart-1** [comment]
[Kite Bridlesystem.pdf](https://github.com/ufechner7/KiteModels.jl/files/14528028/Kite.Bridlesystem.pdf)

This is the wire-bridle system. The three blocks are the three motors we are using.

**Comment by ufechner7** [comment]
I do not fully understand the second page of the pdf. What does "outside" mean? Is that a top view?

Furthermore, would it a valid simplification to assume all three winches are at the same location? Or are they mounted on a platform that can be turned? If so, which distance do the winches have?

**Comment by 1-Bart-1** [comment]
A valid simplification would be that the winches are in the same location. The last page is a side view of the kite, where "outside" is the top surface of the kite, and you can see the red left steering line and the black middle line (you cannot see the blue right steering line as it would be behind the red line). But it looks like I made a mistake with the bridle system on the last page: the black middle line should split between the motor and the kite, as shown correctly on the front view of the kite.
Here is an updated version:
[Kite.Bridlesystem.pdf](https://github.com/ufechner7/KiteModels.jl/files/14628793/Kite.Bridlesystem.pdf)

**Comment by 1-Bart-1** [comment]
Do you have any guidelines on which parts of KPS4.jl I should change?

**Comment by ufechner7** [comment]
We should first agree on the name of the new model. What about KPS4_3L? If that is OK for you I can add such a file and class.

**Comment by ufechner7** [comment]
In the branch 3line you can now find a minimal working example mwes/mwe_10.jl which initializes the model KPS4_3L. I did not change any code, though, but you can find the stuff that needs to be adapted:
- in init.jl all methods that work on KPS4_3L
- all the code in KPS4_3L.jl

But before doing that, have a look at the function get_particles in the package KiteUtils... Well, it might work just as it is now if we do not change the kite itself, just let the lines go to the ground instead of to the KCU.

But most likely some changes to KiteUtils are required, too, for the definition of the SystemState and the Logger, I will create an issue in that package...

**Comment by 1-Bart-1** [comment]
Or maybe it would be better like this?

![image](https://github.com/ufechner7/KiteModels.jl/assets/33758964/94cbc1f4-1ba1-422d-8aa3-74bc89af21f1)

**Comment by ufechner7** [comment]
Implemented by #60
