### ISSUE TITLE
KPS4_3L does not repect changes to the polars after precompilation

### ISSUE THREAD

**Issue by ufechner7** [ufechner7/KiteModels.jl#71]
The functions `rad_cl_mtk` and `rad_cd_mtk` are not part of the model struct and can therefore not be changed after pre-compilation. This should be fixed as it was already done for KPS4 and KPS3. This has no negative impact on the performance.

**Comment by 1-Bart-1** [comment]
Same problem with the symbolic calc_acc_speed and calc_acc_torque functions as they use se("system_3l.yaml"). This is more difficult to solve as the @register_symbolic function only seems to work globally.

**Comment by ufechner7** [comment]
> Same problem with the symbolic calc_acc_speed and calc_acc_torque functions

Can you create a new issue for the problem with these functions?
