### ISSUE TITLE
Use Xfoil polars to calculate c_l, c_d and steering tether forces

### ISSUE THREAD

**Issue by 1-Bart-1** [ufechner7/KiteModels.jl#72]
In order to make the kps4_3l accurate without having to fly a real kite, the Xfoil.jl package should be used to find lift and drag coefficients for different aoa and different steering amounts.

**Comment by ufechner7** [comment]
Sounds good to me. Suggested input:
- one .dat file for the foil shape in the middle of the kite, stored in the data dir
Generated:
- one .yaml file containing all the lift and drag coefficients for different aoa and flap angles, stored in the data dir

Format of the .dat file, describing the wing shape:
1.0000     0.0013
0.9500     0.0114
0.9000     0.0208
0.8000     0.0375
0.7000     0.0518
...
@1-Bart-1 What is the name and unit of the first and second column? And why not using a .csv file?

**Comment by 1-Bart-1** [comment]
If you look here for example:
http://airfoiltools.com/airfoil/details?airfoil=naca0006-il
.dat files seem to be the standard for wing profiles. So I want to stick to the standard. Left is x coordinates, right is y coordinates. Unit does not matter: the profile is normalized so that x is between 0 and 1.

**Comment by 1-Bart-1** [comment]
Yes, the polars depend on the Reynolds number. Paul Thedens told me they use re=18e6 for their kites at SkySails Power, and they use the following formula to calculate it: 
![pro-YWJtyKw4](https://github.com/user-attachments/assets/2bccd14a-12cc-4bd2-bc05-e3597667c887)

**Comment by 1-Bart-1** [comment]
I have changed to using a .csv file for the polars, because it is better suited for the tabular data.

**Comment by 1-Bart-1** [comment]
Better explanation of Re formula here: https://en.wikipedia.org/wiki/Reynolds_number#Flow_around_airfoils
Another thing I am not sure about is how to take the aspect ratio of the wing into account: is this already taken into account because the Reynolds number depends on the chord length?

**Comment by 1-Bart-1** [comment]
Solved with https://github.com/ufechner7/KiteUtils.jl/pull/58
