### ISSUE TITLE
KPS4 Does not take into account the initial wind direction 

### ISSUE THREAD

**Issue by dvanwolffelaar** [ufechner7/KiteModels.jl#88]
In find_steady_state()! in KPS4.jl, the initial wind condition is not taken into account. Fixing this would allow more flexible use of wind conditions and model loading.

**Comment by dvanwolffelaar** [comment]
In addition to the wind direction it would be nice if the v_reel_out was also taken into account

**Comment by ufechner7** [comment]
> In addition to the wind direction it would be nice if the v_reel_out was also taken into account

Please create a separate issue for this feature request.

**Comment by dvanwolffelaar** [comment]
Move reelout speed issue to [99](https://github.com/ufechner7/KiteModels.jl/issues/99)
